# Generated by Django 2.2.3 on 2019-07-19 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h2', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h3', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h4', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h5', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h6', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h7', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h8', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('h9', models.BooleanField(blank=True, choices=[(True, 'Reserved'), (False, 'Unreserved')], default=False)),
                ('related_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Day')),
            ],
        ),
    ]
