# Generated by Django 2.2.3 on 2019-07-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190729_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='reserved',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
