# Generated by Django 2.2.3 on 2019-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20190729_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='reserved',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
