# Generated by Django 2.2.3 on 2019-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20190729_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
